import { useEffect } from "react";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../utils/trpc";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { useAuth } from "@clerk/nextjs";
import { UserButton } from "@clerk/nextjs";
import { execOnce } from "next/dist/shared/lib/utils";
import Navbar from "../componentss/Navbar";

dayjs.extend(relativeTime);

const ListingCard = ({ listing }) => {
  return (
    <div className="rounded-lg border-2 border-gray-200 bg-white p-4 mb-4">
      <div className="flex flex-row">
        <div className="flex items-center justify-center">
          <img
            className="w-12 h-12"
            src={listing.imageUrl}
            alt="Listing Image"
          />
        </div>
        <div className="h-full w-3/4 ml-4">
          <p className="text-right text-gray-500 mb-1 font-serif">
            {`${dayjs(listing.createdAt).fromNow()}`}
          </p>
          <p className="font-bold text-lg mb-1 text-black">{listing.name}</p>
          <p className="mb-2 text-black">${listing.price}</p>
          <p className="mb-4 text-gray-800">{listing.description}</p>
        </div>
      </div>
    </div>
  );
};

 const Home = () => {
  const postQuery = trpc.listing.all.useQuery();
  const { isSignedIn } = useAuth();

  useEffect(() => {
    // Fetch data here if needed
  }, []);

  return (
    <div className="flex h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className="container flex flex-col items-center justify-center gap-12 px-4 py-8">
        <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem] text-center">
          Create <span className="text-[hsl(280,100%,70%)]">T3</span> Turbo
        </h1>

        <div className="flex h-[60vh] justify-center overflow-y-scroll px-4 text-2xl">
          {postQuery.data ? (
            <div className="flex flex-col gap-4">
              {postQuery.data?.map((p) => (
                <ListingCard key={p.id} listing={p} />
              ))}
            </div>
          ) : (
            <p>Loading..</p>
          )}
        </div>
      </main>
    </div>
  );
};

export default Home 